### ISSUE TITLE
Impossible to use dict as a custom arg

### ISSUE THREAD

**Issue by nakeeon** [sendgrid/sendgrid-python#1008]
### Issue Summary
It is impossible to use `dict` as a custom arg.

### Steps to Reproduce
1. Create `Main` instance
2. Call `add_custom_arg` method or `custom_arg` setter to set a custom arg. For example: `{'test': 'true'}`
3. When run the app, the `add_custom_arg` will raise an `AttributeError`.

### Code Snippet
```python
mail = Mail()
mail.add_custom_arg({'test': 'true'})
```

### Exception/Log
```
Traceback (most recent call last):
   ...
    File "/app/sendgrid/helpers/mail/mail.py", line 561, in custom_arg
    self.add_custom_arg(custom_arg)
    File "/app/sendgrid/helpers/mail/mail.py", line 569, in add_custom_arg
    if custom_arg.personalization is not None:
AttributeError: 'dict' object has no attribute 'personalization'
```

### Technical details:
* sendgrid-python version: 6.8.0
* python version: 3.8

**Comment by JenniferMah** [comment]
Hi @nakeeon thanks for submitting a pull request for this issue!
