### ISSUE TITLE
AttributeError: module 'sendgrid' has no attribute 'SendGridAPIClient'y=os.environ.get('SENDGRID_API_KEY'))

### ISSUE THREAD

**Issue by hylaride** [sendgrid/sendgrid-python#210]
#### Issue Summary

Just starting a sendgrid python project and I'm immediately hitting the error in the title

#### Steps to Reproduce

1. ```pip install sendgrid```

2. Code:
```
import sendgrid
import json
import os
sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
```

3. Output:
 
```
chylarides@macbook  ~ $ ./sendgrid.py
Traceback (most recent call last):
  File "./sendgrid.py", line 2, in <module>
    import sendgrid
  File "/Users/chylarides/Sites/sendgrid.py", line 7, in <module>
    sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
AttributeError: module 'sendgrid' has no attribute 'SendGridAPIClient
```

#### Technical details:

* sendgrid-python Version: master sendgrid-3.2.10
* Python Version: 3.5.2

**Comment by hylaride** [comment]
Nevermind.  It was a PEBKAC issue on my part.

**Comment by thinkingserious** [comment]
@hylaride,

Thanks for following up :)
