### ISSUE TITLE
Mail doesnt seem to work python 3.5 - __init__() takes from 1 to 2 positional arguments but 5 were given

### ISSUE THREAD

**Issue by yvan** [sendgrid/sendgrid-python#319]
i have sendgrid's python library v 4.2.0 and the Mail class seems to have an issue with the email helper classes when i try to follow [the examples on heroku's dev center](https://devcenter.heroku.com/articles/sendgrid):

```
sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
from_email = Email("test@example.com")
subject = "Hello World from the SendGrid Python Library!"
to_email = Email("test@example.com")
content = Content("text/plain", "Hello, Email!")
mail = Mail(from_email, subject, to_email, content)
response = sg.client.mail.send.post(request_body=mail.get())
```

i get an error:

```
Traceback (most recent call last):
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yvanscher/anaconda/envs/hexlistserver/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yvanscher/Sites/hexlistserver/hexlistserver/app.py", line 130, in reset_password
    mail = Mail(from_email, subject, to_email, content)
TypeError: __init__() takes from 1 to 2 positional arguments but 5 were given
```

it seems like the init method of the Mail class only takes 1 positional arg, it turns out these args are actually named args. so the examples should read:

```
mail = Mail(from_email=from_email, subject=subject, to_email=to_email, content=content)
```

then i had an issue:
```
__init__() got an unexpected keyword argument 'from_email'
```

which i solved by removing `from sendgrid.helpers.mail import *` line from the example codeand just referencing the mail class from its absolute package path:

```
sendgrid.helpers.mail.Mail(from_email=from_email, subject=subject, to_email=to_email, content=content)
```

this seems to have worked. Looks like this is all related to some import error.

**Comment by thinkingserious** [comment]
Hello @yvan,

Thank you for reaching out and taking the time to share your solution. I have added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @yvan,

I believe this should be solved in v5.X. Please let me know if you continue to experience this issue after upgrading.

Thanks!

With Best Regards,

Elmer

**Comment by strongSoda** [comment]
Hi I'm getting the error 
```
TypeError: __init__() got an unexpected keyword argument 'template_id'
```

when trying to use a template I  created in a python backend.

Has the variable `template_id` been renamed?

**Comment by strongSoda** [comment]
Got it working finally. The docs are way too scattered and broken https://github.com/sendgrid/sendgrid-nodejs/issues/843#issuecomment-650749648
