### ISSUE TITLE
Current Release is Broken

### ISSUE THREAD

**Issue by rdegges** [sendgrid/sendgrid-python#330]
#### Issue Summary

The current PyPI release of Sendgrid is broken. There are some import errors happening. I'm using Python 3.6.1. I've pip installed sendgrid successfully.

#### Steps to Reproduce

1. Open the python REPL
2. Run `import sendgrid`
3. Read the errors:

```python
Python 3.6.1 (default, Apr 21 2017, 21:08:30)
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sendgrid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rdegges/.pyenv/versions/requests/lib/python3.6/site-packages/sendgrid/__init__.py", line 3, in <module>
    from .sendgrid import SendGridAPIClient  # noqa
  File "/home/rdegges/.pyenv/versions/requests/lib/python3.6/site-packages/sendgrid/sendgrid.py", line 2, in <module>
    import python_http_client
  File "/home/rdegges/.pyenv/versions/requests/lib/python3.6/site-packages/python_http_client/__init__.py", line 1, in <module>
    from .client import Client
  File "/home/rdegges/.pyenv/versions/requests/lib/python3.6/site-packages/python_http_client/client.py", line 7, in <module>
    import urllib.request as urllib
  File "/home/rdegges/.pyenv/versions/3.6.1/lib/python3.6/urllib/request.py", line 86, in <module>
    import email
  File "/home/rdegges/Downloads/email.py", line 24, in <module>
    sg = sendgrid.SendGridAPIClient(apikey='XXXXX')
AttributeError: module 'sendgrid' has no attribute 'SendGridAPIClient'
>>>
```

As you can see, it looks like there are import errors in the sendgrid library that need to be fixed. Lazy loading is probably the best way to fix this. Right now though: this library is 100% unusable :(

#### Technical details:

* sendgrid-python Version: latest PyPI release
* Python Version: 3.6.1

**Comment by Pieter19** [comment]
Are you sure, that you have virtualenv configured properly? It looks like it's trying import email.py from your downloads directory instead of python's email package.

Oh and remove your secret api key from paste!

**Comment by thinkingserious** [comment]
Hello @rdegges,

For the safety of your account, we are disabling the API key you posted. Please create a new one. Also, please let me know how it goes with @Pieter19's advice.

And thanks to @Pieter19 for jumping in to help!

With Best Regards,

Elmer
