### ISSUE TITLE
ValueError when attempting Pip install in Azure Debian virual machine

### ISSUE THREAD

**Issue by idealmundo** [sendgrid/sendgrid-python#336]
#### Issue Summary

When I attempt to run
pip install sendgrid in a Debian virtual server on Azure, I get a ValueError:
```
Downloading/unpacking sendgrid
  Downloading sendgrid-5.0.0-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 49, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'python-http-client ==3.0.*', 'at', '*')
```

[pip.log.txt](https://github.com/sendgrid/sendgrid-python/files/1253208/pip.log.txt)

#### Steps to Reproduce

Type 
`pip install sendgrid`
at command prompt. Also happens with sudo pip install sendgrid

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: X.X

**Comment by thinkingserious** [comment]
Hello @idealmundo,

I can not reproduce this locally, so I will need to try and duplicate your environment. I've added this to our backlog for further investigation.

For this issue to gain priority in our backlog, we need additional +1's. 

With Best Regards,

Elmer

**Comment by iamsteadman** [comment]
Yeah, this is happening on my Mac running Virtualbox (Ubuntu 14.04). Looks like maybe the requirements.txt or setup.py file is mangled in the PIP version?

**Comment by thinkingserious** [comment]
@idealmundo, @iamsteadman,

Could you please try v5.0.1? Thanks!
