### ISSUE TITLE
Substitution for transactional templates in API v3 does not work

### ISSUE THREAD

**Issue by mlafore3** [sendgrid/sendgrid-python#565]
``` SEND_GRID_CLIENT = sendgrid.SendGridAPIClient(api_key=CFG['sendgrid_api'])```
```from sendgrid.helpers.mail import *
from django.contrib.auth import settings

sg = settings.SEND_GRID_CLIENT


mail = Mail()
mail.from_email = Email('***')
mail.to_email = Email('***')
mail.subject = 'test email'
mail.add_personalization(Substitution("%greeting%", "HI There"))
mail.set_template_id('***')
response = sg.client.mail.send.post(request_body=mail.get())

    # content = Content('text/html', '<html></html>')
    # mail = Mail(from_email, subject, to_email)
    # p = Personalization()
    # mail.add_personalization(p.add_substitution(Substitution("%greeting%", "HI There")))
    # mail.add_personalization(p.add_substitution(Substitution('%greeting%', 'Hi There')))
    # mail.ap.add_substitution(Substitution('%content%', 'Buh Bye'))
    # mail.add_personalization(p)
    print('here', response.status_code, response.body, response.headers)
```

```
mail.get()
Out[67]: 
{'from': {'email': 'communications@cyclicarx.com'},
 'personalizations': [{'%greeting%': 'HI There'}],
 'subject': 'test email',
 'template_id': '8e9a47ea-2a8a-4f77-8280-c46c2e9e3a21'}
```

```
sg.client.mail.send.post(request_body=mail.get())
---------------------------------------------------------------------------
BadRequestsError                          Traceback (most recent call last)
<ipython-input-68-fa36eeafba59> in <module>()
----> 1 sg.client.mail.send.post(request_body=mail.get())

/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/python_http_client/client.pyc in http_request(*_, **kwargs)
    225                     request.add_header('Content-Type', 'application/json')
    226                 request.get_method = lambda: method
--> 227                 return Response(self._make_request(opener, request))
    228             return http_request
    229         else:

/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/python_http_client/client.pyc in _make_request(self, opener, request)
    159             exc = handle_error(err)
    160             exc.__cause__ = None
--> 161             raise exc
    162 
    163     def _(self, name):

BadRequestsError: 
```

```
"The to array is required for all personalization objects, and must have at least one email object with a valid email address."
```

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 2.7.14

**Comment by mlafore3** [comment]
```(website) marc:~$ ./manage.py send_email
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/mlaforet/Cyclica/probe_web/probex/management/commands/send_email.py", line 14, in handle
    test_email()
  File "/Users/mlaforet/Cyclica/probe_web/probex/emails.py", line 21, in test_email
    response = sg.client.mail.send.post(request_body=mail.get())
  File "/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/python_http_client/client.py", line 204, in http_request
    return Response(self._make_request(opener, request))
  File "/Users/mlaforet/.virtualenvs/probe_web/lib/python2.7/site-packages/python_http_client/client.py", line 138, in _make_request
    return opener.open(request)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request```

**Comment by mlafore3** [comment]
I guess my question is how to set the to parameter for substitutions programmatically
