### ISSUE TITLE
'UnauthorizedError' object has no attribute 'message'

### ISSUE THREAD

**Issue by OlafvdSpek** [sendgrid/sendgrid-python#795]
When using a wrong API key:

```
except Exception as e:
    print(e.message) # AttributeError: 'UnauthorizedError' object has no attribute 'message'
```

https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_a_single_email_to_a_single_recipient.md

**Comment by thinkingserious** [comment]
Thanks for reporting this @OlafvdSpek! I've added this to our backlog for further investigation.

**Comment by thinkingserious** [comment]
Ah, it looks like it should be simply `print(e)`

**Comment by jonathan-murmu** [comment]
it should be only 
`print(e)`

**Comment by helle253** [comment]
Should this issue be closed? It looks like its been resolved, unless I'm mistaken.

**Comment by OlafvdSpek** [comment]
Which commit / merge fixed it?

**Comment by helle253** [comment]
Turns out, I am mistaken :) I'm working on some fixes to the use cases - I found this issue with multiple different .md files, and there were some additional fixes needed to get the script in sending_html.content.md working properly. Still need to finish going through all the other use cases to ensure they run without major issues, though.

**Comment by helle253** [comment]
Dug through most of the use cases, and they still work apart from 2 -

kitchen_sink.md - two errors thrown, preventing it from sending the hello world email: 
1. categories must be unique
2. the batch_id not being valid

The former is easily fixed, but I'm having more trouble resolving the latter. Guidance would be appreciated.

aws.md - workflows for AWS have changed significantly since this was written, I think. I had trouble getting code to deploy - I'm not super familiar with AWS, so I wasn't able to resolve the issues. It seemed like the code snippets provided worked, however.

I can add a PR for these changes - Apart from these two issues, I think I've resolved most of the smaller issues in the existing use cases.

**Comment by noobanon** [comment]
# Can anyone help me in this errors

2020-01-17T08:59:39.923373+00:00 app[web.1]: 2020-01-17 08:59:39,923 - haruka - INFO - Successfully loaded
2020-01-17T08:59:39.924101+00:00 app[web.1]: 2020-01-17 08:59:39,924 - haruka - INFO - Using long polling.
2020-01-17T08:59:49.368355+00:00 app[web.1]: 2020-01-17 08:59:49,366 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
2020-01-17T08:59:49.368372+00:00 app[web.1]: Traceback (most recent call last):
2020-01-17T08:59:49.368394+00:00 app[web.1]:   File "/app/haruka/__main__.py", line 627, in process_update
2020-01-17T08:59:49.368397+00:00 app[web.1]:     for handler in (x for x in self.handlers[group] if x.check_update(update)):
2020-01-17T08:59:49.368399+00:00 app[web.1]:   File "/app/haruka/__main__.py", line 627, in <genexpr>
2020-01-17T08:59:49.368401+00:00 app[web.1]:     for handler in (x for x in self.handlers[group] if x.check_update(update)):
2020-01-17T08:59:49.368403+00:00 app[web.1]:   File "/app/haruka/modules/helper_funcs/handlers.py", line 63, in check_update
2020-01-17T08:59:49.368406+00:00 app[web.1]:     res = self.filters(message)
2020-01-17T08:59:49.368408+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/filters.py", line 87, in __call__
2020-01-17T08:59:49.368410+00:00 app[web.1]:     return self.filter(update)
2020-01-17T08:59:49.368412+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/filters.py", line 1011, in filter
2020-01-17T08:59:49.368414+00:00 app[web.1]:     return update.message is not None or update.edited_message is not None
2020-01-17T08:59:49.368422+00:00 app[web.1]: AttributeError: 'Message' object has no attribute 'message'
2020-01-17T08:59:49.369044+00:00 app[web.1]: 2020-01-17 08:59:49,368 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
2020-01-17T08:59:49.369047+00:00 app[web.1]: Traceback (most recent call last):
2020-01-17T08:59:49.369049+00:00 app[web.1]:   File "/app/haruka/__main__.py", line 628, in process_update
2020-01-17T08:59:49.369051+00:00 app[web.1]:     handler.handle_update(update, self)
2020-01-17T08:59:49.369057+00:00 app[web.1]: TypeError: handle_update() missing 1 required positional argument: 'check_result'

**Comment by childish-sambino** [comment]
Fixed here: https://github.com/sendgrid/sendgrid-python/commit/a81abdd370ddfcba02d1a5f24fa73ceca29810dc

**Comment by andrelbd1** [comment]
My problem was solved using this: https://stackoverflow.com/questions/56564083/how-do-i-fix-an-http-error-401-unauthorized-when-sending-an-email-using-sendgri

**Comment by jimbrayrcp** [comment]
This issue may have been resolved but the documentation on this page was never updated to reflect the resolution.

[Check this link: Integrate using our Web API or SMTP Relay](https://app.sendgrid.com/guide/integrate/langs/python)

**Comment by arnoan** [comment]
I also encountered the `AttributeError: 'UnauthorizedError' object has no attribute 'message'` error today when trying to get SendGrid to work with Python and it took me quite a while to figure out what was wrong.

As @jimbrayrcp said: 
Both the [Setup Guide](https://app.sendgrid.com/guide/integrate/langs/python), as well as the [SendGrid Python Developer Documentation](https://docs.sendgrid.com/for-developers/sending-email/v3-python-code-example) still contain the faulty code.
 
It should be `print(e.body)` instead of `print(e.message)`.

I would also recommend pulling the reading of the environment variable out of the "Try" block and using a direct dictionary lookup, rather than the the `.get()` method since that returns `None` if no env_var is found and thus fails silently.

The updated example code should read like this: 
```python
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

message = Mail(
    from_email='from_email@example.com',
    to_emails='to@example.com',
    subject="Sending with Twilio SendGrid is Fun",
    html_content="<strong>and easy to do anywhere, even with Python</strong>",
)
API_KEY = os.environ["SENDGRID_API_KEY"] # This will fail directly, if there is a problem with the env_var
try:
    sg = SendGridAPIClient(API_KEY)
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e.body)   # This will ensure the actual error is displayed
```
