### ISSUE TITLE
Recipient delete returns Bad Request

### ISSUE THREAD

**Issue by jer-tx** [sendgrid/sendgrid-python#819]
#### Issue Summary

Deleting a single recipient returns a bad request error. 

#### Steps to Reproduce

Using the [example](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#delete-recipient), I wrote my code like this:

```
data = [
    base64.b64encode(email)
]
response = sg.client.contactdb.recipients.delete(request_body=data)
```

This returns a 400 bad request response. I know the "recipient_id" is accurate as a base64 encoded string of the email, as it matches exactly with this request's response for recipient ID:

````sg.client.contactdb.recipients.get(base64.b64encode(email)````

That^ returns just fine the entire recipient data. I tried putting the base64 encoded email in-line without it being inside a list, just like I have here, and that didn't work either. Same 400 bad request.

#### Technical details:

* sendgrid-python Version: 6.0.5
* Python Version: 2.7

#### Traceback:

Traceback (most recent call last):
```
File "C:\Users\redacted\PycharmProjects\redacted\src\webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "C:\Users\redacted\PycharmProjects\redacted\src\webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "C:\Users\redacted\PycharmProjects\redacted\src\webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "C:\Users\redacted\PycharmProjects\redacted\src\webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "C:\Users\redacted\PycharmProjects\redacted\src\webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "C:\Users\redacted\PycharmProjects\redacted\src\redacted\api_handlers\tasks_handler.py", line 197, in handle_exception
    super(BaseTaskHandler, self).handle_exception(exception, debug_mode)
  File "C:\Users\redacted\PycharmProjects\redacted\src\webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "C:\Users\redacted\PycharmProjects\redacted\src\redacted\api_handlers\marketing_cloud_handler.py", line 114, in post
    self.call_method(name)
  File "C:\Users\redacted\PycharmProjects\redacted\src\redacted\api_handlers\tasks_handler.py", line 186, in call_method
    action_method()
  File "C:\Users\redacted\PycharmProjects\redacted\src\redacted\api_handlers\marketing_cloud_handler.py", line 141, in subscriber_update_email
    marketing_cloud_api.subscriber_update_email(self.original_email, self.account.get().email, None)
  File "C:\Users\redacted\PycharmProjects\redacted\src\redacted\api\external\marketing_cloud_api.py", line 304, in subscriber_update_email
    self.delete_subscriber(original_email)
  File "C:\Users\redacted\PycharmProjects\redacted\src\redacted\api\external\marketing_cloud_api.py", line 214, in delete_subscriber
    response = sg.client.contactdb.recipients.delete(request_body=base64.b64encode(email or self.email))
  File "C:\Users\redacted\PycharmProjects\redacted\src\tools\libraries\python_http_client\client.py", line 252, in http_request
    return Response(self._make_request(opener, request, timeout=timeout))
  File "C:\Users\redacted\PycharmProjects\redacted\src\tools\libraries\python_http_client\client.py", line 176, in _make_request
    raise exc
BadRequestsError
```

**Comment by jer-tx** [comment]
Looking at the documentation further, I see a [second endpoint](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#delete-contactdbrecipientsrecipient_id) to delete a single recipient... (?) 

That one _does_ work properly. Problem with the documentation? 

To clarify, retrieving a single recipient from the "multiple recipient" endpoint like this:

`sg.client.contactdb.recipients.get(query_params=params)`

works just fine. But _deleting_ a single recipient in presumably the same way like this:

`sg.client.contactdb.recipients.delete(request_body=data)`

doesn't work at all.

**Comment by thinkingserious** [comment]
Hello @jer-tx,

Thanks for reporting this! We've added this to our backlog for further investigation.

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @jer-tx,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
