### ISSUE TITLE
AttributeError: 'SendGridAPIClient' object has no attribute 'send'

### ISSUE THREAD

**Issue by newtonkiragu** [sendgrid/sendgrid-python#856]
Hello,

I am using sendgrid to send mail via django, however, it keeps saying 
```AttributeError: 'SendGridAPIClient' object has no attribute 'send'```

#### Steps to Reproduce

1. install sendgrid
`pip install sendgrid`
2. run script

```python
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

sg = SendGridAPIClient("the_api_key")

email_data = Mail(
    from_email="support@email.africa",
    to_email="example@email.com",
    subject="YOUR EVENT IS NOW LIVE ON SITE!",
)
email_data.dynamic_template_data = json.dumps({
    "username": "example username",
    "item_name": "example item name",
    "item_slug": "path to example item slug",
    "template_id": "transactional template id",
    "message_type": "EMAIL"
})

response = sg.send(request_body=email_data.get())
```
error:
```
Traceback (most recent call last):
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/mixins.py", line 84, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/mixins.py", line 70, in update
    self.perform_update(serializer)
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/mixins.py", line 80, in perform_update
    serializer.save()
  File "/Users/Retina15/project/virtual/lib/python3.6/site-packages/rest_framework/serializers.py", line 209, in save
    self.instance = self.update(self.instance, validated_data)
  File "/Users/Retina15/project/store/serializers/event.py", line 358, in update
    response = sg.send(request_body=email_data.get())
AttributeError: 'SendGridAPIClient' object has no attribute 'send'
```
#### Technical details:

* sendgrid Version: 3.6.5
* Python Version: 3.6

**Comment by newtonkiragu** [comment]
Answered [here](https://stackoverflow.com/questions/58935356/attributeerror-sendgridapiclient-object-has-no-attribute-send/58940926#58940926)

**Comment by yusuf963** [comment]
I am having the same error, let me know if ever somebody response this inquiry

**Comment by JenniferMah** [comment]
Hi @yusuf963 Did you have a chance to checkout the [stack-overflow post](https://stackoverflow.com/questions/58935356/attributeerror-sendgridapiclient-object-has-no-attribute-send/58940926#58940926)? If you still need assistance with this error please open a new issue.
