### ISSUE TITLE
Object of type Bcc is not JSON serializable

### ISSUE THREAD

**Issue by d8nnii** [sendgrid/sendgrid-python#877]
### Issue Summary
This error shows up no matter whether I'm passing it a string value from a list or hard code the email address.

### Code Snippet
```python
def send_email(msg):
    
      sg = SendGridAPIClient(api_key=sg_key)
      from_email = Email(json_data[0]["email"])
      to_email = To(email="receiver@email.com")
      bcc_email = Bcc(email="test@email.com")
      subject = "Greetings!!!"
      content = HtmlContent(msg)

      mail = Mail(from_email, to_email, bcc_email, subject, content)
      response = sg.client.mail.send.post(request_body=mail.get())

send_email("Hi there")
```

### Exception/Log
```
Traceback (most recent call last):
  File "scratchpad.py", line 46, in send_email
    response = sg.client.mail.send.post(request_body=mail.get())
  File "/Users/d8nnii/Documents/GitHub/manual_otp/.venv/lib/python3.7/site-packages/python_http_client/client.py", line 251, in http_request
    data = json.dumps(request_body).encode('utf-8')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Bcc is not JSON serializable
```

### Technical details:
* sendgrid-python version: 6.1.3
* python version: 3.7

**Comment by childish-sambino** [comment]
The `Mail` constructor does not have a Bcc or Cc param: https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L24-L32

You can use `mail.add_bcc("test@email.com")` to add a bcc.
