### ISSUE TITLE
Error handling HTTPError: http.client.IncompleteRead

### ISSUE THREAD

**Issue by raafi15** [sendgrid/sendgrid-python#970]
### Issue Summary
Hi, I'm using sendgrid with my Django app, and trying to test my code's ability to handle errors communicating with the sendgrid server. However, when I'm testing the sendgrid_client.send() with a deliberately false API key, it fails to raise the HTTPError (and therefore is not caught by by try/except statement. Instead, whilst attempting to initialise the HTTPError an IncompleteRead exception is raised by sendgrid. 
I was wondering if I have set something up incorrectly to cause this? It does not occur when I am unittesting my sendgrid function in isolation, only when I am testing it as part of a DRF API view. In all cases when a valid API key is provided this code works fine, I am just trying to mimic HTTPErrors and check they can be handled correctly

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```python
# email is a Mail() object generated by previous code during request handling
# Send HTTP request
    try:
        sg = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
        sg.send(email)
    # Catch errors
    except HTTPError as e:
        # Log them
        logger.error(
            f"{message.capitalize()} sendgrid API call fail with response code: {e.status_code}")
        logger.error(
            f"Sendgrid API error reason: {e.reason}")
        return False
    else:
        logger.info(f'Successful {message} sendgrid API call')
        return True
```

### Exception/Log
```
Traceback (most recent call last):
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\python_http_client\client.py", line 176, in 
_make_request
    return opener.open(request, timeout=timeout)
  File "C:\Python\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Python\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Python\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\test\utils.py", line 381, in inner   
    return func(*args, **kwargs)
  File "C:\Users\Nader Raafat\Documents\VS Code\teaching_app\tests\users\test_registration.py", line 558, in test_user_registration_error_response
    response = self.client.post('/users/register/', data)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\test.py", line 295, in post  
    response = super().post(
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\test.py", line 209, in post  
    return self.generic('POST', path, data, content_type, **extra)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\test.py", line 233, in generic
    return super().generic(
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\test\client.py", line 470, in generic    return self.request(**r)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\test.py", line 285, in request
    return super().request(**kwargs)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\test.py", line 237, in request
    request = super().request(**kwargs)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\test\client.py", line 716, in request    self.check_exception(response)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\test\client.py", line 577, in check_exception
    raise exc_value
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\core\handlers\base.py", line 181, in 
_get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Nader Raafat\Documents\VS Code\teaching_app\users\rest_views.py", line 92, in post
    sendgrid_success = sendgrid_mail(subject, template, personalizations, 'Tutor activation')
  File "C:\Users\Nader Raafat\Documents\VS Code\teaching_app\users\help.py", line 255, in sendgrid_mail
    sg.send(email)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\python_http_client\client.py", line 277, in 
http_request
    self._make_request(opener, request, timeout=timeout)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\python_http_client\client.py", line 178, in 
_make_request
    exc = handle_error(err)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\python_http_client\exceptions.py", line 82, 
in handle_error
    exc = err_dict[error.code](error)
  File "c:\Users\Nader Raafat\Documents\VS Code\teaching_app\env\lib\site-packages\python_http_client\exceptions.py", line 10, 
in __init__
    self.body = error.read()
  File "C:\Python\lib\tempfile.py", line 473, in func_wrapper
    return func(*args, **kwargs)
  File "C:\Python\lib\http\client.py", line 471, in read
    s = self._safe_read(self.length)
  File "C:\Python\lib\http\client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 116 more expected)
```

### Technical details:
* sendgrid-python version: 6.4.8
* python version: 3.8.7

**Comment by JenniferMah** [comment]
Hi @raafi15
Did you have a chance to checkout our [trouble shooting documentation](https://github.com/sendgrid/sendgrid-python/blob/main/TROUBLESHOOTING.md#error)? It links to how this library handles HTTP exceptions.

**Comment by raafi15** [comment]
> 
> 
> Hi @raafi15
> Did you have a chance to checkout our [trouble shooting documentation](https://github.com/sendgrid/sendgrid-python/blob/main/TROUBLESHOOTING.md#error)? It links to how this library handles HTTP exceptions.

Hi @JenniferMah , thanks for getting back to me! I did read through this when writing my code which is why I've used a try/except statement to catch the HTTPError. My issue right now is that sg.send is not raising an HTTPError, it's raising an IncompleteRead because the __init__ method of HTTPError is failing (self.body = error.read() raises IncompleteRead) and I'm not sure why that is? 
As explained above in a separate unittest the same snippet of code works this only fails when it's part of a view unittest rather than a method-only unit test.
Do let me know if you need more information!

**Comment by shwetha-manvinkurke** [comment]
@raafi15 Are you importing the `HTTPError` from `python_http_client.exceptions import HTTPError` and not `urllib.error`?

**Comment by raafi15** [comment]
@shwetha-manvinkurke yes I'm importing from ptyhon_http_client.exceptions - I assume that's the right one?
As I said, an HTTPError is not being raised, instead an IncompleteRead error is being raised during the __init__ process of the HTTPError. I could of course import and catch that but I feel there might be something going wrong here and it feels like a hack-ish solution.

**Comment by thinkingserious** [comment]
Hello @raafi15,

I am unable to reproduce using the following code:

```python
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (From, To, Subject, PlainTextContent, HtmlContent, Mail)
from python_http_client import exceptions

sendgrid_client = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
from_email = From("example@example.com")
to_email = To("example@example.com")
subject = Subject("Sending with Twilio SendGrid is Fun")
plain_text_content = PlainTextContent("and easy to do anywhere, even with Python")
html_content = HtmlContent("<strong>and easy to do anywhere, even with Python</strong>")
message = Mail(from_email, to_email, subject, plain_text_content, html_content)
try:
    response = sendgrid_client.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except exceptions.BadRequestsError as e:
    print(e.body)
    exit()
```

Error traceback

```bash
Traceback (most recent call last):
  File "temp.py", line 14, in <module>
    response = sendgrid_client.send(message)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/sendgrid/base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/python_http_client/client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/python_http_client/client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
```

In your exception log, I see `urllib.error.HTTPError: HTTP Error 401: Unauthorized`. It appears you need to verify you have `from python_http_client import exceptions` in combination with changing `except HTTPError as e:` to `except exceptions.BadRequestsError as e:`.

I hope that helps!

With best regards,

Elmer

**Comment by raafi15** [comment]
Hi Elmer,
Apologies for the delay in responding  and thank you for your response. Strangely, without making any modification to my codebase, the error is no longer happening. Not sure why that happened in the first place but I guess it has now resolved so all is well!
